In [1]:
# Importing the necessary libraries
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [5]:
# Creating the dataset
dataset = [['Milk', 'Bread', 'Butter'],
           ['Bread', 'Eggs'],
           ['Milk', 'Eggs', 'Butter'],
           ['Milk', 'Bread', 'Eggs', 'Butter'],
           ['Milk', 'Bread', 'Eggs']]# Encoding the dataset
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)# Finding the frequent itemsets
frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)# Generating the association rules
frequent_itemsets

    support                     itemsets
0       0.8                      (Bread)
1       0.6                     (Butter)
2       0.8                       (Eggs)
3       0.8                       (Milk)
4       0.4              (Bread, Butter)
5       0.6                (Bread, Eggs)
6       0.6                (Bread, Milk)
7       0.4               (Butter, Eggs)
8       0.6               (Milk, Butter)
9       0.6                 (Milk, Eggs)
10      0.2        (Bread, Butter, Eggs)
11      0.4        (Milk, Bread, Butter)
12      0.4          (Milk, Bread, Eggs)
13      0.4         (Milk, Butter, Eggs)
14      0.2  (Milk, Bread, Butter, Eggs)